baseURL = "https://lephucnz.github.io/blog/"
languageCode = "vi"
title = "Blog cá»§a PhÃºc"
theme = "PaperMod"
buildDrafts = true

[params]
  author = "LÃª Mai HoÃ ng PhÃºc"
  description = "Chia sáº» kiáº¿n thá»©c vÃ  kinh nghiá»‡m láº­p trÃ¬nh Java & JavaScript"
  featured_image = "images/tn.png"
  mainSections = ["posts"]
  show_reading_time = true
  show_toc = true
  show_share_buttons = true
  date_format = "02-01-2006"
  defaultTheme = "auto"
  disableScrollToTop = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  disableFingerprinting = true

[params.homeInfoParams]
Title = "ğŸ‘‹ ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cá»§a tÃ´i!"
Content = "MÃ¬nh lÃ  LÃª Mai HoÃ ng PhÃºc â€“ sinh viÃªn CÃ´ng nghá»‡ ThÃ´ng tin. Blog nÃ y chia sáº» kiáº¿n thá»©c vá» Java, JavaScript vÃ  láº­p trÃ¬nh máº¡ng."



  socialIcons = [
    { name = "github", url = "https://github.com/LePhucnz" },
    { name = "linkedin", url = "https://linkedin.com/in/lephucnz" },
    { name = "email", url = "mailto:lhphuc0910@gmail.com" }
  ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
minMatchCharLength = 2
keys = ["title", "summary", "content"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Trang chá»§"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨â€ğŸ’» Giá»›i thiá»‡u"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "ğŸ“° Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "ğŸ” TÃ¬m kiáº¿m"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

