baseURL = "https://lephucnz.github.io/blog-hugo/"
languageCode = 'vi'
title = 'My New Hugo Site'
theme = "paperMod"

buildDrafts = true

[params]
  author = "LÃª Mai HoÃ ng PhÃºc"
  description = "Chia sáº» kiáº¿n thá»©c vÃ  kinh nghiá»‡m láº­p trÃ¬nh Java & JavaScript"
  featured_image = "images/tn.png" # áº£nh cÃ³ sáºµn trong Ananke
  mainSections = ["posts"]
  show_reading_time = true
  show_toc = true
  show_share_buttons = true
  date_format = "02-01-2006"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Trang chá»§"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨â€ğŸ’» Giá»›i thiá»‡u"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "ğŸ“° Blog"
    url = "/posts/"
    weight = 3